### ISSUE TITLE
How did you evaluate CARE-GNN on the wiki dataset?

### ISSUE THREAD

**Issue by LuckyJinging** [wyl7/DCI-pytorch#1]
Hi,

I try to read the experimental setup in your paper. I am wondering how you did evaluate the performance of CARE-GNN designed for multi-relation graphs, on the wiki dataset? 

Thank you very much,

**Comment by wyl7** [comment]
Hi LuckyJinging,

Thanks for your question! Since our dataset is homogeneous graph which only contains one relation type, we do not use the inter-relation AGG in CARE-CNN. We mainly want to compare with the RL-based neighbor selector in CARE-GNN, as the RL-based neighbor selector has the potential to alleviate the inconsistency problem.

Hope I have solved you question!😁

**Comment by LuckyJinging** [comment]
Thanks for your quick response👍! May I know if you adopted the early stopping strategy in the other baselines and what were their training epochs?

**Comment by wyl7** [comment]
hi LuckyJinging,

If I remember correctly, I tested the early stopping for other baselines, and found it may make the second-stage training overfitting for some baselines, so I unified the maximum training epochs. DCI is a thought for self-supervised training, I think you can also try the early stopping and set a better setting for your experiments. 

Thank you!😁

**Comment by LuckyJinging** [comment]
Thank you! I also want to know if you adopted the early stopping strategy in joint training algorithms for fairness?

**Comment by wyl7** [comment]
Both joint training algorithms and decoupled training algorithms use the cross-entropy to optimize the encoder and classifier, and they run in the same setting for a fair comparison. The difference between joint training and decoupled training is that the latter one adopts SSL to pre-train the graph encoder for a better parameter initialization to serve the second-stage end2end training.😁

**Comment by LuckyJinging** [comment]
Thanks for your patiently reply~! ❤

**Comment by wyl7** [comment]
No problem! Inspired by DCI, we have developed another SSL objective ClusterSCL. https://github.com/wyl7/ClusterSCL

Feel free to email me, if you have any question!😄

**Comment by LuckyJinging** [comment]
Thank you! They are excellent jobs and I will try to follow your work!
